multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: manipulator
    base_link: base_link
    tip_link: force_sensor
default_collision_operations:
  - object1: base_link
    object2: link0
    operation: disable  # Adjacent in collision
  -
    object1: link0
    object2: link1
    operation: disable  # Adjacent in collision
  -
    object1: link1
    object2: link2
    operation: disable  # Adjacent in collision
  -
    object1: link2
    object2: link3
    operation: disable  # Adjacent in collision
  -
    object1: link3
    object2: link4
    operation: disable  # Adjacent in collision
  -
    object1: link4
    object2: force_sensor
    operation: disable  # Adjacent in collision
  -
    object1: force_sensor
    object2: lead_tip
    operation: disable  # Adjacent in collision
  -
    object1: base_link
    object2: link1
    operation: disable  # Never in collision
  -
    object1: force_sensor
    object2: link2
    operation: disable  # Never in collision
  -
    object1: force_sensor
    object2: link3
    operation: disable  # Never in collision
  -
    object1: lead_tip
    object2: link2
    operation: disable  # Never in collision
  -
    object1: lead_tip
    object2: link3
    operation: disable  # Never in collision
  -
    object1: lead_tip
    object2: link4
    operation: disable  # Never in collision
  -
    object1: link0
    object2: link2
    operation: disable  # Never in collision
  -
    object1: link1
    object2: link4
    operation: disable  # Never in collision
  -
    object1: link2
    object2: link4
    operation: disable  # Never in collision