service_type: FilterJointTrajectoryWithConstraints
filter_chain:
  - 
    name: unnormalize_trajectory
    type: UnNormalizeFilterJointTrajectoryWithConstraints
  -
    name: cubic_spline_smoother
    type: CubicSplineVelocityScalerFilterJointTrajectory
    params: {num_iterations: 100, discretization: 0.001}


