/* Auto-generated by genmsg_cpp for file /home/mahisorn/ros_workspace/hg-ros-pkg/win_ros/kinect_msgs/msg/SkeletonTrackingState.msg */
#ifndef KINECT_MSGS_MESSAGE_SKELETONTRACKINGSTATE_H
#define KINECT_MSGS_MESSAGE_SKELETONTRACKINGSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kinect_msgs
{
template <class ContainerAllocator>
struct SkeletonTrackingState_ {
  typedef SkeletonTrackingState_<ContainerAllocator> Type;

  SkeletonTrackingState_()
  {
  }

  SkeletonTrackingState_(const ContainerAllocator& _alloc)
  {
  }

  enum { SKELETON_NOT_TRACKED = 0 };
  enum { SKELETON_POSITION_ONLY = 1 };
  enum { SKELETON_TRACKED = 2 };

  typedef boost::shared_ptr< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SkeletonTrackingState
typedef  ::kinect_msgs::SkeletonTrackingState_<std::allocator<void> > SkeletonTrackingState;

typedef boost::shared_ptr< ::kinect_msgs::SkeletonTrackingState> SkeletonTrackingStatePtr;
typedef boost::shared_ptr< ::kinect_msgs::SkeletonTrackingState const> SkeletonTrackingStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kinect_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5ef7185bd672713cd4304a672c9b653f";
  }

  static const char* value(const  ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5ef7185bd672713cULL;
  static const uint64_t static_value2 = 0xd4304a672c9b653fULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kinect_msgs/SkeletonTrackingState";
  }

  static const char* value(const  ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int8 SKELETON_NOT_TRACKED = 0\n\
int8 SKELETON_POSITION_ONLY = 1\n\
int8 SKELETON_TRACKED = 2\n\
\n\
";
  }

  static const char* value(const  ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SkeletonTrackingState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kinect_msgs::SkeletonTrackingState_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // KINECT_MSGS_MESSAGE_SKELETONTRACKINGSTATE_H

