(cl:in-package kinect_msgs-msg)
(cl:export '(SKELETON_TRACKING_STATE-VAL
          SKELETON_TRACKING_STATE
          TRACKING_ID-VAL
          TRACKING_ID
          ENROLLMENT_INDEX-VAL
          ENROLLMENT_INDEX
          USER_INDEX-VAL
          USER_INDEX
          POSITION-VAL
          POSITION
          SKELETON_POSITIONS-VAL
          SKELETON_POSITIONS
          SKELETON_POSITION_TRACKING_STATE-VAL
          SKELETON_POSITION_TRACKING_STATE
          QUALITY_FLAG-VAL
          QUALITY_FLAG
))