/* Auto-generated by genmsg_cpp for file /home/mahisorn/ros_workspace/hg-ros-pkg/prw_apps/prw_message/msg/Object.msg */
#ifndef PRW_MESSAGE_MESSAGE_OBJECT_H
#define PRW_MESSAGE_MESSAGE_OBJECT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Pose.h"
#include "geometry_msgs/Vector3.h"
#include "sensor_msgs/PointCloud2.h"

namespace prw_message
{
template <class ContainerAllocator>
struct Object_ {
  typedef Object_<ContainerAllocator> Type;

  Object_()
  : header()
  , pose()
  , size()
  , cloud()
  , name()
  , type(0)
  {
  }

  Object_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pose(_alloc)
  , size(_alloc)
  , cloud(_alloc)
  , name(_alloc)
  , type(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::Pose_<ContainerAllocator>  pose;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _size_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  size;

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  cloud;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef int32_t _type_type;
  int32_t type;

  enum { UNKNOW = 0 };
  enum { CUBE = 1 };
  enum { SPHERE = 1 };

  typedef boost::shared_ptr< ::prw_message::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prw_message::Object_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Object
typedef  ::prw_message::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::prw_message::Object> ObjectPtr;
typedef boost::shared_ptr< ::prw_message::Object const> ObjectConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::prw_message::Object_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::prw_message::Object_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace prw_message

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::prw_message::Object_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::prw_message::Object_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::prw_message::Object_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d6737f97696543959e66de394ecb5b58";
  }

  static const char* value(const  ::prw_message::Object_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd6737f9769654395ULL;
  static const uint64_t static_value2 = 0x9e66de394ecb5b58ULL;
};

template<class ContainerAllocator>
struct DataType< ::prw_message::Object_<ContainerAllocator> > {
  static const char* value() 
  {
    return "prw_message/Object";
  }

  static const char* value(const  ::prw_message::Object_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::prw_message::Object_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# A pose, reference frame, timestamp, and type\n\
Header header\n\
geometry_msgs/Pose pose\n\
geometry_msgs/Vector3 size\n\
sensor_msgs/PointCloud2 cloud\n\
string name\n\
int32 type\n\
\n\
# object definitions\n\
int32 UNKNOW = 0\n\
int32 CUBE = 1\n\
int32 SPHERE = 1\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::prw_message::Object_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::prw_message::Object_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::prw_message::Object_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::prw_message::Object_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pose);
    stream.next(m.size);
    stream.next(m.cloud);
    stream.next(m.name);
    stream.next(m.type);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Object_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prw_message::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::prw_message::Object_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "size: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "cloud: ";
s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PRW_MESSAGE_MESSAGE_OBJECT_H

